# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: go-app-cicd
  labels:
    app: go-app-cicd
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: go-app-cicd
  type: ClusterIP
